# action.yml
name: 'Prestashop PHP 7.2 Linter'
description: 'PHP linter for 7.2'
inputs:
  folder-to-exclude:
    description: 'Folder to exclude'
    required: false
    default: '! -path "./vendor/*"'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.folder-to-exclude }}